version: '3.1'
services:
  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    platform: linux/amd64
    container_name: zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
    ports:
      - "2181:2181"

  kafka:
    image: confluentinc/cp-kafka:latest
    platform: linux/amd64
    container_name: kafka
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    ports:
      - "9092:9092"
    depends_on:
      - zookeeper

  mysql:
    image: mysql:8.0
    container_name: mysql-container
    environment:
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - ./db_movies_netflix_transact.sql:/docker-entrypoint-initdb.d/db_movies_netflix_transact.sql
    ports:
      - "3310:3306"

  debezium:
    image: debezium/connect:latest
    platform: linux/amd64
    container_name: debezium
    environment:
      BOOTSTRAP_SERVERS: kafka:9092
      GROUP_ID: 1
      CONFIG_STORAGE_TOPIC: debezium_config
      OFFSET_STORAGE_TOPIC: debezium_offset
      STATUS_STORAGE_TOPIC: debezium_status
      CONNECT_KEY_CONVERTER_SCHEMAS_ENABLE: "false"
      CONNECT_VALUE_CONVERTER_SCHEMAS_ENABLE: "false"
      CONNECT_KEY_CONVERTER: org.apache.kafka.connect.json.JsonConverter
      CONNECT_VALUE_CONVERTER: org.apache.kafka.connect.json.JsonConverter
      CONNECT_REST_ADVERTISED_HOST_NAME: debezium
      CONNECT_REST_PORT: 8083
      CONNECT_LOG4J_ROOT_LOGLEVEL: INFO
    ports:
      - "8083:8083"
    depends_on:
      - kafka
      - mysql

  akhq:
    image: tchiotludo/akhq:latest
    depends_on:
      - kafka
    ports:
      - "8080:8080"
    environment:
      AKHQ_CONFIGURATION: |
        akhq:
          connections:
            docker-kafka:
              properties:
                bootstrap.servers: "kafka:9092"
  jupyter:
    build: .
    container_name: jupyter-container
    volumes:
      - .:/home/jovyan/work
    ports:
      - "8888:8888"
    environment:
      JUPYTER_ENABLE_LAB: "yes"
    depends_on:
      - mysql
      - kafka

  postgres:
    image: postgres:latest
    container_name: postgres-olap
    environment:
      POSTGRES_DB: dw_netflix
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
    volumes:
      - ./data_warehouse_netflix.sql:/docker-entrypoint-initdb.d/olap_init.sql
    ports:
      - "5432:5432"
    depends_on:
      - mysql

volumes:
  mysql_data:
